Edit(IDP-1203): Move Extension Tutorial
mia-platform/documentation pull request #1403
Opened 2024-05-20 15:10 UTC by MIA-Deltat1995

## Description

## Pull Request Type

- [x] Documentation content changes
- [ ] Bugfix / Missing Redirects
- [ ] Docusaurus site code changes

## PR Checklist

- [x] The commit message follows our guidelines included in the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#how-to-submit-a-pr)
- [x] All tests of Lint, cspell and check-content pass. ([How to launch them?](../blob/main/CONTRIBUTING.md#content-checks))
- [x] No sensitive content has been committed

## Other information

2024-05-20 15:24 UTC, fredmaggiowski requested changes

2024-05-20 16:15 UTC, akelity commented on docs/console/tutorials/create-extension.md
+1

2024-05-20 16:29 UTC, MIA-Deltat1995 commented on docs/console/tutorials/create-extension.md
done

2024-05-21 07:46 UTC, akelity approved these changes
LGTM

2024-05-21 07:47 UTC, fredmaggiowski approved these changes
LGTM

2024-05-21 07:47 UTC, merged