feat(MPE-243): fix create company doc
mia-platform/documentation pull request #285
Opened 2023-05-24 16:06 UTC by Giogia

## Description

## Pull Request Type

- [ ] Documentation content changes
- [ ] Bugfix / Missing Redirects
- [ ] Docusaurus site code changes

## PR Checklist

- [ ] The commit message follows our guidelines included in the [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md#how-to-submit-a-pr)
- [ ] All tests of Lint, cspell and check-content pass. ([How to launch them?](../blob/main/CONTRIBUTING.md#content-checks))
- [ ] No sensible content has been committed

## Other information

2023-05-24 16:18 UTC, Danielecina commented on docs/development_suite/company/create.mdx
> +You can create a new company by making a POST request to the `/api/backend/companies` API.
l'host della console cambia tra on premise e paas. Vogliamo specificare che ci vuole l'host? 

Mettiamo un esempio? di curl? 

```suggestion
You can create a new company by making a POST request to the `${THE_CONSOLE_HOST}/api/backend/companies` API. 
```

2023-05-25 09:49 UTC, davidebianchi requested changes

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +    - **options**: TODO
This is an object with view and name:

```json
{
  "view": {
    "name": ""
  }
}
```

and will be used during the generation of the service to name the Jenkins pipeline on the correct view

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +  - **providerId** (_required_): unique identifier of the secret manager provider associated with the company.
This is not required, for example using gitlab which is the same git provider

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +    If in your company all the environment variables are set to be located in the parent group, by editing this field you can safely change the variables path for all the projects in the company in o
```suggestion
    If in your company all the environment variables are set to be located in the parent group, by editing this field you can safely change the variables path for all the projects in the company.
```

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +  The content of this array will be interpolated during project creation by replacing `%projectId%` strings with the `projectId` field specified in the project.
Can we check if it's only projectId? I don't think so

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +   - **hosts**: TODO
An array of object, which specify at the project creation which host will be exposed (if exposed in template), used by links in environment sections

Something like:

```json
    "hosts": [
      {
        "host": "test.%projectId%.console.gcp.mia-platform.eu",
        "isBackoffice": false,
        "scheme": "https"
      }
    ],
```

Where isBackoffice and scheme are optional.

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +   - **links**:     TODO
This is not set inside company if I well remember

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +   - **cluster**:     TODO
Something like:

```json
    "cluster": {
      "clusterId": "objectId-of-the-cluster",
      "namespace": "%projectId%-dev",
      "kubeContextVariables": {
        "KUBE_URL": "",
        "KUBE_TOKEN": "",
        "KUBE_CA_PEM": ""
      }
    }
```

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +   - **dashboard**:     TODO
This is not from the company side, but are taken from the project template

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +    TODO jobId, statusWebhookSecretCredentialsId, paramsMap
jobId and paramsMap are set for Jenkins

statusWebhookSecretCredentialsId is set by github-actions, but during the project creation it should not be here. But it should be verified, I'm not sure

2023-05-25 09:49 UTC, davidebianchi commented on docs/development_suite/company/create.mdx
> +  Namesapces are useful when your company is made up of several projects that communicate with each other.
```suggestion
  Namespaces are useful when your company is made up of several projects that communicate with each other.
```

2023-05-25 09:50 UTC, jacoposte commented on docs/development_suite/company/create.mdx
> +- clusters
Metterei come ordine per primi i cluster rispetto ai provider, giusto per ordine logico

2023-05-25 09:52 UTC, jacoposte commented on docs/development_suite/company/create.mdx
> +- providers (git providers, secret managers, CI/CD tools)
Dato che questo probabilmente è il primo accenno ai provider in un flusso utente spiegherei brevissimamente cosa intendiamo noi come providers e per cosa vengono utilizzati nella console. Magari un primo utente non ne hai idea e non collega leggendo un generico "provider"

2023-05-25 09:54 UTC, jacoposte commented on docs/development_suite/company/create.mdx
> +It is also possible to manually create a company from the Console Backoffice.
Nel titoplo si parla di CMS e qui di Backoffice, io utilizzerei lo stesso acronimo. 
Fiontanto che il Backoffice non sostituisce a pieno il CMS mi riferirei sempre al CMS

2023-05-25 09:59 UTC, jacoposte commented on docs/development_suite/company/create.mdx
> +  ##### Example Configuration
Qui, giusto per essere a prova di super-dummy, farei un esempio per ogni provider mettendo tipo le tab che abbiamo già da altra parti.

2023-05-25 09:59 UTC, jacoposte commented on docs/development_suite/company/create.mdx
> +  ##### Example Configuration
Anche qui idem, mettere un esempio per ogni provider supportato

2023-05-25 10:02 UTC, Giogia commented on docs/development_suite/company/create.mdx
> +- `console.root.company.create` permission
Sure, I can add this information. @fredmaggiowski , do you know better about Davide's question?

2023-05-25 10:02 UTC, Giogia commented on docs/development_suite/company/create.mdx
> +## Create a company from CMS
Can try that!

2023-05-25 10:04 UTC, Giogia commented on docs/development_suite/company/create.mdx
> +:::
Do you think placing it between the API paragraph and this one could work for you?

2023-05-25 10:13 UTC, Giogia commented on docs/development_suite/company/create.mdx
> +It is also possible to manually create a company from the Console Backoffice.
ok :+1:

2023-05-25 10:14 UTC, Giogia commented on docs/development_suite/company/create.mdx
> +- clusters
ok :+1:

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +:::
It would probably be more effective to place it directly under the "Create a company from CMS" title 😁

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +- clusters
Nel caso invertirei anche sotto i relativi paragrafi

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +Git providers, Secret Managers and CI/CD tools can be configured from the **Providers** section inside Company Overview area of the Console.
```suggestion
Git Providers, Secret Managers, and CI/CD Tools can be configured from the **Providers** section within the Company Overview area of the Console.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +Clusters can be connected to a company from the **Clusters** section inside Company Overview area of the Console.
```suggestion
Clusters can be connected to a company from the **Clusters** section within the Company Overview area of the Console.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
>  ### Connect a cluster
```suggestion
### Connect a Cluster
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  - **providerId** (_required_): unique identifier of the git provider associated with the company
```suggestion
  - **providerId** (_required_): unique identifier of the Git Provider associated with the company.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +    - `internal`: the repository can be accessed and viewed by any authenticated user within the same git provider instance or organization;
```suggestion
    - `internal`: the repository can be accessed and viewed by any authenticated user within the same Git Provider instance or organization;
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +    Here some tips on how to correctly configure the _basePath_ property, grouped by Git provider:
```suggestion
    Here some tips on how to correctly configure the _basePath_ property, grouped by Git Provider:
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +      For example, if your organization is reachable at the URL **`https://github.com/mia-platform`**, then the `basePath` must be **`mia-platform`**
```suggestion
      For example, if your organization is reachable at the URL **`https://github.com/mia-platform`**, then the `basePath` must be **`mia-platform`**.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +    <TabItem value="bitbucket" label="BitBucket">
```suggestion
    <TabItem value="bitbucket" label="Bitbucket">
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +      It corresponds to the **path where your BitBucket project is reachable**: the pattern is _projects/project-code_.
```suggestion
      It corresponds to the **path where your Bitbucket project is reachable**: the pattern is _projects/project-code_.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  - **providerId** (_required_): unique identifier of the CI/CD tool provider associated with the company.
```suggestion
  - **providerId** (_required_): unique identifier of the CI/CD Tool associated with the company.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  This field can also be set by [selecting a default secret manager provider](/docs/development_suite/set-up-infrastructure/providers-management#set-a-default-provider) in the **Providers** section o
```suggestion
  This field can also be set by [selecting a default Secret Manager](/docs/development_suite/set-up-infrastructure/providers-management#set-a-default-provider) in the **Providers** section of the Console.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  This field is not required. However, by leaving an empty configuration you will need to manually configure a secret manager provider for each project you create.
```suggestion
  This field is not required. However, by leaving an empty configuration you will need to manually configure a Secret Manager for each project you create.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  - **providerId** (_required_): unique identifier of the secret manager provider associated with the company.
```suggestion
  - **providerId** (_required_): unique identifier of the Secret Manager associated with the company.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +      - **url** (_required_): URL where the metrics are retreived from;
```suggestion
      - **url** (_required_): URL from which the metrics are retrieved;
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +      - **category**: indicates the group in which the dashboard will be presented in the console UI.
```suggestion
      - **category**: indicates the group in which the dashboard will be presented in the Console UI.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  - **deploy**: An object that describes the configuration of CI/CD pipelines for the environment.
```suggestion
  - **deploy**: an object that describes the configuration of CI/CD pipelines for the environment.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +  Instead, prefer the use of an interpolated value. By specifying a variable key name (as shown in the example), the value will be taken from the corresponing project variable.
```suggestion
  Instead, prefer the use of an interpolated value. By specifying a variable key name (as shown in the example), the value will be taken from the corresponding project variable.
```

2023-05-25 12:53 UTC, RiccardoCorona-MiaPlatform commented on docs/development_suite/company/create.mdx
> +    - **path**: Either one of the following:
```suggestion
    - **path**: either one of the following:
```

2023-05-26 14:03 UTC, closed without merging