Update request and limits content
mia-platform/documentation pull request #33
Opened 2023-03-08 10:40 UTC by hiimjako

## Pull Request Type

- [ ] Bugfix
- [X] Documentation content changes

## Description

Update to request and limits content to be more clear, based on @davidebianchi review.

## PR Checklist

- [X] The commit message follows our guidelines included in the [CONTRIBUTING.md](../CONTRIBUTING.md#how-to-submit-a-pr)
- [X] All tests of Lint, cspell and check-content pass. ([How to launch them?](../CONTRIBUTING.md#content-checks))
- [X] No sensible content has been committed

## Other information

2023-03-08 11:13 UTC, davidebianchi requested changes
Thank you for the changes

2023-03-08 11:13 UTC, davidebianchi commented on docs/development_suite/api-console/api-design/request_limits.mdx
> +  - `Guaranteed` QoS, if requests equals limits and both explicitly defined in configuration, meaning that the pod is guaranteed to receive the required resources. If such resources cannot be reserve
In this case, the Guaranteed is specifically set only if each resource in all containers in pods have the same request and limits. The Burstable in the other cases with limit and request set.

I don't know if it is explicitly set only limits, but as the request is set by default equal to the limit in this case I think the pod is set as Guaranteed (but this should be verified)

2023-03-08 11:13 UTC, davidebianchi commented on docs/development_suite/api-console/api-design/request_limits.mdx
> +  - `Burstable` QoS in case only the limits it is explicitly defined.
It is not the only case (and maybe it's a guaranteed case), read the comment above

2023-03-08 11:24 UTC, hiimjako commented on docs/development_suite/api-console/api-design/request_limits.mdx
> +  - `Guaranteed` QoS, if requests equals limits and both explicitly defined in configuration, meaning that the pod is guaranteed to receive the required resources. If such resources cannot be reserve
Fine, understood!
I was missing the point in the previous PR comment, going to update it!

2023-03-09 07:47 UTC, davidebianchi commented on docs/development_suite/api-console/api-design/request_limits.mdx
> +  - `Guaranteed` QoS, if requests equals limits both for CPU and memory for each container in the pod. This means that the pod is guaranteed to receive the requested resources. If such resources cann
```suggestion
  - `Guaranteed` QoS, if requests equals limits both for CPU and memory for each container in the pod. This means that the pod is guaranteed to receive the requested resources. If such resources cannot be reserved, it will not be scheduled. This pods will be the last to face eviction;
```

2023-03-09 07:48 UTC, davidebianchi approved these changes
LGTM

2023-03-09 07:50 UTC, merged